name: Main

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint-test-build:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 19.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkouts
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build
        run: npm run build