name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
permissions:
      checks: write
      pull-requests: write
      contents: write
jobs:
  lint-test-build:
    name: Lint, Build, Test and Coverage Report
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [19.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2 
      
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Lint Code
        run: pnpm run lint


      - name: Format Code
        run: pnpm run format

      - name: Build
        run: pnpm run build

      - name: Run Tests
        run: pnpm run test:ci
      
      - name: Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80
          coverage-file: coverage.json
          base-coverage-file: coverage.json
          skip-step: alls